<?php $url = $this->url(array('controller' => 'language', 'action' => 'select', 'code' => 'nl')) ?>
<h1><a href="<?php echo $url ?>">Portaal klav.be</a></h1>
<p><a href="<?php echo $url ?>">Informatie en diensten van KLAV</a></p>

<br />
<br />

<?php $url = $this->url(array('controller' => 'language', 'action' => 'select', 'code' => 'fr')) ?>
<h1><a href="<?php echo $url ?>">Portail klav.be</a></h1>
<p><a href="<?php echo $url ?>">Informations et services officiels</a></p>
