<?php

$user = Zend_Auth::getInstance()->getIdentity();
$this->headScript()->appendFile($this->baseUrl() . '/js/dialog.js');

$this->headTitle('SxCms - '.$this->admin_tmx->_('hometextblocks').' - '.$this->admin_tmx->_('overviewhometextblocks'));
echo $this->render('system/result.phtml');

?>

<div id="dialog" title="<?php echo $this->admin_tmx->_('deletefolder') ?>" style="display: none;">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?php echo $this->admin_tmx->_('deletefolderconfirm') ?></p>
</div>

<h3><?php echo $this->admin_tmx->_('textblockshomepageoverview') ?> [<?php echo $_SESSION['System']['lng'] ?>]</h3>
<table width="98%">
    <tr>
        <th><?php echo $this->admin_tmx->_('blockname') ?></th>
        <th><?php echo $this->admin_tmx->_('title') ?></th>
        <th><?php echo $this->admin_tmx->_('action') ?></th>
    </tr>
    <?php foreach ($this->paginator as $id => $item): ?>
    <tr>
        <td><?php echo $this->escape($item->getBlockname()) ?></td>
        <td><?php echo $this->escape($item->getTitle()) ?></td>
        <td>
            <a title="<?php echo $this->admin_tmx->_('edit') ?>" href="<?php echo $this->url(array('action' => 'edit', 'id' => $item->getId())) ?>">
                <img src="<?php echo $this->baseUrl('/images/cms/actions/page_white_edit.png') ?>" alt="<?php echo $this->admin_tmx->_('edit') ?>" />
            </a>
            <!--
            <a title="<?php echo $this->admin_tmx->_('delete') ?>" class="delete" href="#" onclick="showDialog('#dialog', '<?php echo $this->url(array('action' => 'delete', 'id' => $item->getId())) ?>');">
                <img src="<?php echo $this->baseUrl('/images/cms/actions/page_white_delete.png') ?>" alt="<?php echo $this->admin_tmx->_('delete') ?>" />
            </a>-->
        </td>
    </tr>
    <?php endforeach ?>
</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'system/pagination.phtml'); ?>