<h3 id="menu-faq"><a href="#">FAQ-vragen</a></h3>
<div>
	<ul class="sidemenu">
		<li><a href="<?php echo $this->url(array('controller' => 'faq', 'action' => 'index'), null, true) ?>">Overzicht</a></li>
      	<li><a href="<?php echo $this->url(array('controller' => 'faq', 'action' => 'add'), null, true) ?>">Toevoegen</a></li>
	</ul>
    <strong>Types</strong>
    <ul class="sidemenu">
		<li><a href="<?php echo $this->url(array('controller' => 'faq_type', 'action' => 'index'), null, true) ?>">Overzicht</a></li>
      	<li><a href="<?php echo $this->url(array('controller' => 'faq_type', 'action' => 'add'), null, true) ?>">Toevoegen</a></li>
	</ul>
</div>


