<?php echo $this->Doctype('HTML5'); ?>
<!--[if lt IE 7 ]> <html lang="nl" class="ie6"> <![endif]-->
<!--[if IE 7 ]> <html lang="nl" class="ie7"> <![endif]-->
<!--[if IE 8 ]> <html lang="nl" class="ie8"> <![endif]-->
<!--[if IE 9 ]> <html lang="nl" class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="nl"> <!--<![endif]-->
<head>
    <?php echo $this->action('head' , 'index' , null , array('page' => $this->page, 'lng' => $this->lng)) ?>
</head>
<body>
<?php echo $this->render('__layout/analytics.phtml') ?>
	<div id="holder">
    	<div id="main">
                <!--HEADER-->
			
            <?php echo $this->render('__layout/header.phtml') ?>
            <div class="container_12">
            	<div class="grid_12" id="breadcrumbs">
                	<?php echo $this->action( 'breadcrumbs', 'index', null, array('page' => $this->page, 'lng' => $this->lng) ) ?>
 				</div>
                <div class="clear"></div>
                <div class="grid_4" id="faq-types">
                	<?php echo $this->action( 'types', 'faq', null, array('lng' => $this->lng) ) ?>
                </div>
            	<div class="grid_8" id="content-view">
             	<?php echo $this->layout()->content ?>
                </div>
                
            </div>
             
        </div>
    </div>      
   
<?php echo $this->render('__layout/footer.phtml') ?>



</body>
</html>