<?php
    $basePathLanguage = '/' . $this->lng; 
    $basePath = '/'; 
?>
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<?php echo $this->action('head' , 'index' , null , array('page' => $this->page, 'lng' => $this->lng)) ?>
	</head>
	<body>	
        <div id="main-container">
            <hr class="top-hr"></hr>
            <div class ="logo-container container_12">
                <a href="<?php echo $this->baseUrl($basePathLanguage); ?>" class="logo"></a>
            </div>
            <div class="menu-container container_12">
                <?php echo $this->action('multilevelmenu' , 'index' , null , array('page' => $this->page, 'lng' => $this->lng)) ?>
            </div>
            <div id="pt-main" class="pt-perspective container_12">
                <div class="pt-page pt-page-1 grid_12">
                    <div class="home-content-container">
                        <div class="header-text">
                           
                            <?php echo $this->page->getContent(); ?>
                        </div>
                        <div class="img-work-container grid_12">
                            <div class="home-work"></div>
                            <a class="shadow-radial home-work-hover" href="<?php echo $this->url(array('lng' => $this->lng), 'work-overview', true); ?>"></a> 
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <?php echo $this->render('__layout/footer.phtml'); ?>
        </div>
        
	</body>
</html>
