<?php $this->headScript()->appendFile($this->baseUrl() . '/js/tiny_mce/tiny_mce.js') ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/js/tiny_mce/tiny_mce_init.js') ?>

<?php $this->headScript()->captureStart() ?>
$(function(){
	$("#publication_date").datepicker({ dateFormat: 'yy/mm/dd' });
});
<?php $this->headScript()->captureEnd()  ?>

<div id="tabs">
    <ul>
        <li><a href="#tabs-common">Algemeen
            <?php $errors = count($this->messages->getTabMessages('common')) ?>
            <?php if ($errors): ?>
                <span class="errcount">(<?php echo $errors ?>)</span>
            <?php endif ?>
            </a>
        </li>
        <li><a href="#tabs-content">Inhoud
            <?php $errors = count($this->messages->getTabMessages('content')) ?>
            <?php if ($errors): ?>
                <span class="errcount">(<?php echo $errors ?>)</span>
            <?php endif ?>
            </a>
        </li>
    </ul>
    <form name="category" method="post" action="<?php echo $this->url() ?>" enctype="multipart/form-data">
    <div id="tabs-common">
        <dl>
            <dt>
                <label for="category">Categorie:</label>
            </dt>
            <dd>
                <select name="category">
                <?php foreach ($this->categories as $category): ?>
                    <option value="<?php echo $category->getId() ?>"><?php echo $category->getName() ?></option>
                <?php endforeach ?>
                </select>
                <?php echo $this->messages->getMessagesHtml('category') ?>
                <p class="description">
                    Verplicht te selecteren
                </p>
            </dd>
            <dt>
                <label for="name">Naam:</label>
            </dt>
            <dd>
                <input type="text" name="name" id="name" size="45"
                    value="<?php echo $this->escape($this->publication->getName()) ?>" />
                <?php echo $this->messages->getMessagesHtml('name') ?>
                <p class="description">
                    Verplicht in te vullen, minimum 2 en maximum 255 karakters
                </p>
            </dd>
            
              <dt>
                <label for="name">Publicatiedatum:</label>
            </dt>
            <dd>
            <?php
				$pubdate = $this->publication->getPublicationDate();
				$pubdateYmd =  strftime('%Y/%m/%d',strtotime($pubdate)); 
			?>
                <input type="text" name="publication_date" id="publication_date" size="45"
                    value="<?php echo $pubdate ? $pubdateYmd : date('Y/m/d') ?>" />
                <?php echo $this->messages->getMessagesHtml('name') ?>
                
            </dd>
            
            
            <dt>
                <label for="description">Omschrijving:</label>
            </dt>
            <dd>
                <textarea name="description" id="description" cols="90" rows="15" style="width:98%; height: 250px;" class="mceEditor"><?php echo $this->publication->getDescription() ?></textarea>
                <?php echo $this->messages->getMessagesHtml('description') ?>
                <p class="description">
                    Verplicht in te vullen, minimum 2 en maximum 255 karakters
                </p>
            </dd>
            <dd style="margin-top: 20px;">
                <input class="button" type="submit" value="Opslaan" onclick="disableConfirm();" />
            </dd>
        </dl>
    </div>
    <div id="tabs-content">
        <dl>
            <dd>
                <textarea name="content" id="content" cols="90" rows="15" style="width:98%; height: 450px;" class="mceEditor"><?php echo $this->publication->getContent() ?></textarea>
                <?php echo $this->messages->getMessagesHtml('description') ?>
                <p class="description">
                    Verplicht in te vullen, minimum 2 en maximum 255 karakters
                </p>
            </dd>

            <dd style="margin-top: 20px;">
                <input type="hidden" name="lang" value="<?php echo $_SESSION['System']['lng'] ?>" />
                <input class="button" type="submit" value="Opslaan" onclick="disableConfirm();" />
            </dd>
        </dl>
    </div>
    </form>
</div>

