<h3 id="menu-faq"><a href="#"><?php echo $this->admin_menu_tmx->_('faq.faq') ?></a></h3>
<div>
    <ul class="sidemenu">
        <li><a href="<?php echo $this->url(array('controller' => 'faqcategory', 'action' => 'index')) ?>"><?php echo $this->admin_menu_tmx->_('faq.overview') ?></a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'faq', 'action' => 'add')) ?>"><?php echo $this->admin_menu_tmx->_('faq.addqa') ?></a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'faqcategory', 'action' => 'add')) ?>"><?php echo $this->admin_menu_tmx->_('faq.addcat') ?></a></li>
    </ul>
</div>