<?php if ($this->page->getType() == SxCms_Page::ARTICLE && $this->page->allowComments()): ?>

<h2><?php echo count($this->comments) ?> reacties tot nu toe</h2>
<?php foreach ($this->comments as $comment): ?>
<?php $author = $comment->getCommenter(); ?>

<div class="comment">
    <div class="author">
        <div class="gravatar">
            <img src="http://www.gravatar.com/avatar/<?php echo md5($author->getEmail()) ?>?size=60" alt="" />
        </div>
	</div>

    <div class="message">
		<strong>
		<?php if ($author->getWebsite()): ?>
			<a href="<?php echo $this->escape($author->getWebsite()) ?>">
				<?php echo stripslashes($this->escape($author->getName())) ?></a>
		<?php else: ?>
			<?php echo $this->escape($author->getName()) ?>
		<?php endif ?>
		</strong>
		schreef <br/>

        <?php echo $this->escape($comment->getMessage()) ?>

        <div class="date">
            op <i><?php echo strftime('%a %d %b %Y om %H:%M:%S', strtotime($comment->getDatePosted())) ?></i>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>

<?php endforeach ?>

<?php if (!$this->isBot): ?>
<h2>Laat een bericht achter</h2>
<form name="comment" method="post" action="">

<?php $author = $this->comment->getCommenter() ?>
<table class="comments">
	<tr>
		<td valign="top" width="150">Naam:</td>
		<td valign="top">*</td>
		<td><input type="text" name="name" size="40"
			value="<?php echo $this->escape($author->getName()) ?>" />

			 <?php echo $this->errors('name') ?>
		</td>
	</tr>
	<tr>
		<td valign="top">Email:</td>
		<td valign="top">*</td>
		<td><input type="text" name="email" size="40"
			value="<?php echo $this->escape($author->getEmail()) ?>" />
			<?php echo $this->errors('email') ?>
		</td>
	</tr>
	<tr>
		<td valign="top">Website:</td>
		<td></td>
		<td><input type="text" name="website" size="40"
			value="<?php echo $this->escape($author->getWebsite()) ?>" />
			<?php echo $this->errors('website') ?>
		</td>
	</tr>
	<tr>
		<td valign="top">Bericht:</td>
		<td valign="top">*</td>
		<td><textarea name="message" cols="50" rows="10"><?php echo $this->escape($this->comment->getMessage()) ?></textarea>
			<?php echo $this->errors('message') ?>
		</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td><?php echo $this->captcha->render() ?>
		</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td><input type="text" name="captcha" size="40"
			value="<?php echo $this->escape($this->userCaptcha) ?>" /><br />
			<div style="font-size: 8px;">
				Typ de tekst in bovenstaande afbeelding over in dit tekstvak
			</div>
			<?php echo $this->errors('captcha') ?>
		</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
		<td><input type="submit" name="comment-submit" value="Verzenden" /></td>
	</tr>
</table>
</form>
<?php endif ?>
<?php endif ?>