<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<title>Thieu Smith Designer</title>
<meta name="description" content="Thieu Smith Designer" />
<meta name="keywords" content="page transition, css animation, website, effect, css3, jquery, Thieu Smith Designer" />
<meta name="author" content="QUANGSONPRO" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/css/default.css'); ?>" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/css/component.css'); ?>" />
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/css/animations.css'); ?>" />

        
<?php
    echo $this->headTitle();
    echo $this->headMeta();
    echo $this->headLink();
    echo $this->headStyle();
?>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/css/Site.css'); ?>" />
<link rel="shortcut icon" href="/images/website/smith.ico" type="image/x-icon" />

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery-1.8.2.min.js'); ?>"></script>