<?php echo $this->Doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php echo $this->headTitle(); ?>
	    <?php echo $this->headMeta(); ?>
	    <?php echo $this->headLink() ?>
	    <?php echo $this->headScript() ?>
	    <?php echo $this->headStyle() ?>
	    
	    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/css/Error.css') ?>" />
	</head>
	<body>
		<div id="container">
            <h1>The website is temporarily unavailable</h1>

            <p>
                Sorry. The website is temporarily unavailable.<br />
                The problem has already been reported to our team. Please try again in fifteen minutes.<br />
                Thanks for your understanding.
            </p>

            <p>thieusmith | T: 093 440 1701 | <a href="mailto:thieusmith@gmail.com">thieusmith@gmail.com</a></p>
		</div>
	</body>
</html>