<?php echo $this->Doctype('XHTML1_STRICT'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php echo $this->headTitle(); ?>
	    <?php echo $this->headMeta(); ?>
	    <?php echo $this->headLink() ?>
	    <?php echo $this->headScript() ?>
	    <?php echo $this->headStyle() ?>
	    
	    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/css/Error.css') ?>" />
	</head>
	<body>
		<div id="container">
			<?php if($this->lng == 'nl'): ?>
				<h1>Website tijdelijk niet beschikbaar</h1>

				<p>
					Sorry. De website is tijdelijk niet beschikbaar.<br />
					Dit probleem werd gemeld aan ons team. Probeer het na een kwartiertje nog eens.<br />
					Alvast bedankt voor uw begrip.
				</p>

				<p>Sanmax | T: +32 [0]70 250 236 | <a href="mailto:info@sanmax.be">info@sanmax.be</a></p></p>
			<?php else: ?>
				<h1>The website is temporarily unavailable</h1>

				<p>
					Sorry. The website is temporarily unavailable.<br />
					The problem has already been reported to our team. Please try again in fifteen minutes.<br />
					Thanks for your understanding.
				</p>

				<p>Sanmax | T: +32 [0]70 250 236 | <a href="mailto:info@sanmax.be">info@sanmax.be</a></p>
			<?php endif; ?>
		</div>
	</body>
</html>