<div id="geochart" style="width: 94%; margin-left: 2%;"></div>

<script type="text/javascript">

function drawGeoChart() {

	var data = new google.visualization.DataTable();
	data.addColumn('number', 'LATITUDE', '<?php echo $this->admin_tmx->_('longitute') ?>');
	data.addColumn('number', 'LONGITUDE', '<?php echo $this->admin_tmx->_('latitude') ?>');
	data.addColumn('string', 'DESCRIPTION','<?php echo $this->admin_tmx->_('city') ?>');
	data.addColumn('number', 'VALUE','<?php echo $this->admin_tmx->_('visits') ?>');
    data.addRows([
		<?php
		
        $total = count($this->cities["city"]);
        foreach ($this->cities["visits"] AS $key => $value) {

			echo "[".$this->cities["latitude"][$key].", ".$this->cities["longitude"][$key].", '".addslashes($this->cities["city"][$key])."', $value]";
            if ($key < $total-1) echo ",";

        }
		
		?>
	]);

    var options = {
        
        region: "<?php echo $this->iso; ?>",
        colors: ["#D7E8F7", "#375D81"],
        keepAspectRatio: "true",
		displayMode: 'markers', 
		enableRegionInteractivity: 'true',
		resolution: 'provinces',
		magnifyingGlass: {enable: true, zoomFactor: 5.0},
		sizeAxis: {maxSize: 30, minSize: 3}
                
    };

    var chart = new google.visualization.GeoChart(document.getElementById('geochart'));
    chart.draw(data, options);
	
	$('#back').click(function(){
    	window.location = "/admin/analytics/geo";
	});

}

google.load("visualization", "1", {packages:["geochart"]});
google.setOnLoadCallback(drawGeoChart);

</script>