<h2><?php echo $this->admin_tmx->_('mobiledevices') ?></h2>
<div id="devicesbar" style="width: 100%; height: 200px;"></div>

<script type="text/javascript">

google.load("visualization", "1", {packages:["corechart"]});
google.setOnLoadCallback(drawDevicesBar);

function drawDevicesBar() {

    var data = google.visualization.arrayToDataTable([
        ['<?php echo $this->admin_tmx->_('device') ?>', '<?php echo $this->admin_tmx->_('visits') ?>'],
        <?php
        
        $total = count($this->devices["device"]);
        foreach ($this->devices["visits"] AS $key => $value) {

            echo "['".addslashes($this->devices["device"][$key])."', ".$value."]";
            if ($key < $total-1) echo ",";

        }

        ?>
    ]);

    var options = {
        
        chartArea: {left: 100, top: 0, width: '70%', height: 140},
        colors: ['#6A8BAB'],
        legend: {position: 'none'}
                
    };

    var chart = new google.visualization.BarChart(document.getElementById('devicesbar'));
    chart.draw(data, options);

}

</script>