<div id="geochart" style="width: 94%; margin-left: 2%;"></div>

<script type="text/javascript">

function drawGeoChart() {

    var data = google.visualization.arrayToDataTable([
        ['<?php echo $this->admin_tmx->_('country') ?>', '<?php echo $this->admin_tmx->_('visits') ?>'],
        <?php
        
        $total = count($this->countries["country"]);
        foreach ($this->countries["visits"] AS $key => $value) {

            echo "['".addslashes($this->countries["country"][$key])."', ".$value."]";
            if ($key < $total-1) echo ",";

        }

        ?>
    ]);

    var options = {
        
        region: "world",
        colors: ["#D7E8F7", "#375D81"],
        keepAspectRatio: "true",
		displayMode: 'regions', 
		enableRegionInteractivity: 'true',
		resolution: 'countries'
        //colors: ['#6A8BAB'],
        //legend: {position: 'none'}
                
    };

    var chart = new google.visualization.GeoChart(document.getElementById('geochart'));
    chart.draw(data, options);

	google.visualization.events.addListener(chart, 'regionClick', function (dataSelect) {		
		//console.log(dataSelect);
		
		window.regionClicked = dataSelect.region;
    });


	google.visualization.events.addListener(chart, 'select', function () {	
		console.log(window.regionClicked);
			
		var selection = chart.getSelection();		
        if (selection.length == 1) {
          	var selectedRow = selection[0].row;
          	var selectedCountry = data.getValue(selectedRow, 0);
          	chart.setSelection();
          	console.log(selectedCountry);
          	window.location = "/admin/analytics/geo/country/" + selectedCountry + "/iso/" + window.regionClicked;
        }
    });

	function defineContinent(continent) {
		Object.defineProperty(options, "region", {
		    value: continent,
		    writable: true,
		    enumerable: true,
		    configurable: true
		});
		chart.draw(data, options);
	}
	
	$('#world').click(function(){
		defineContinent("world");
	});
	
	$('#af').click(function(){
		defineContinent("002");
	});
	
	$('#eu').click(function(){
		defineContinent("150");
	});
	
	$('#am').click(function(){
		defineContinent("019");
	});
	
	$('#as').click(function(){
		defineContinent("142");
	});
	
	$('#oc').click(function(){
		defineContinent("009");
	});

}

google.load("visualization", "1", {packages:["geochart"]});
google.setOnLoadCallback(drawGeoChart);

</script>