<?php echo $this->render('system/leave.phtml'); ?>

<?php $this->headScript()->captureStart() ?>
$(function(){
	$('#tabs').tabs();
    $('#link').tabs();
	$("#date_published").datepicker({ dateFormat: 'yy/mm/dd' });
	$("#date_expired").datepicker({ dateFormat: 'yy/mm/dd' });
});

<?php if ($this->page->getId() !== 0): ?>
function generateUrl() {
    var title = '';
    $.get('<?php echo $this->url(array('controller' => 'page', 'action' => 'get-url-ajax')) ?>', { title: $("#title").val() }, function(data) {
        $("#url").html(data);
    });
}

$(function() {
	var theTable = $('#pages')
	$("#title").keyup(function() {
        generateUrl();
  	});

	$("#parent_id").change(function() {
        generateUrl();
  	});

    generateUrl();
});

<?php endif ?>
<?php $this->headScript()->captureEnd() ?>

<?php if (false !== $this->page->getId()): ?>
<h3><?php echo $this->admin_tmx->_('editpage') ?>: "<?php echo $this->page->getTitle() ?>"</h3>
<?php else: ?>
<h3><?php echo $this->admin_tmx->_('addpage') ?></h3>
<?php endif ?>

<div id="link" style="margin: 0 0 10px 8px; padding: 10px; font-size: 14px; font-weight: bold;">
    <?php echo Zend_Registry::get('config')->system->web->url ?><span id="url"></span>
</div>

<div id="tabs">
	<ul>
		<li><a href="#tabs-title-summary"><?php echo $this->admin_tmx->_('titlesummary') ?>
			<?php $errors = count($this->messages->getTabMessages('title-summary')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
		<?php if ($this->page->getType() == SxCms_Page::EXTERNAL): ?>
		<li><a href="#tabs-external"><?php echo $this->admin_tmx->_('externalurl') ?>
			<?php $errors = count($this->messages->getTabMessages('external')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
		<?php endif ?>
		<?php if ($this->page->getType() != SxCms_Page::EXTERNAL && $this->page->getType() != SxCms_Page::SUMMARY): ?>
		<li><a href="#tabs-content"><?php echo $this->admin_tmx->_('content') ?>
			<?php $errors = count($this->messages->getTabMessages('content')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
		<?php endif ?>
		<?php if ($this->page->getType() != SxCms_Page::ARTICLE): ?>
		<li><a href="#tabs-menu-tags"><?php echo $this->admin_tmx->_('menu') ?> <!-- &amp; Tags -->
			<?php $errors = count($this->messages->getTabMessages('menu-tags')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
		<?php endif ?>
		<?php if ($this->page->getType() == SxCms_Page::INTERNAL): ?>
		<li><a href="#tabs-layout"><?php echo $this->admin_tmx->_('layout') ?>
			<?php $errors = count($this->messages->getTabMessages('layout')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
		<?php endif ?>
		<li><a href="#tabs-acl"><?php echo $this->admin_tmx->_('rights') ?>
			<?php $errors = count($this->messages->getTabMessages('acl')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
		<li><a href="#tabs-publish"><?php echo $this->admin_tmx->_('publication') ?>
			<?php $errors = count($this->messages->getTabMessages('publish')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
        
        <li><a href="#tabs-seo"><?php echo $this->admin_tmx->_('seo') ?>
			<?php $errors = count($this->messages->getTabMessages('seo')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
        
		<li><a href="#tabs-notes"><?php echo $this->admin_tmx->_('save') ?></a></li>
	</ul>
	<form name="add" method="post" action="<?php echo $this->url() ?>" enctype="multipart/form-data">
	<div id="tabs-title-summary">
		<?php echo $this->render('page/forms/__summary.phtml') ?>
	</div>
	<?php if ($this->page->getType() == SxCms_Page::EXTERNAL): ?>
	<div id="tabs-external">
		<?php echo $this->render('page/forms/__external.phtml') ?>
	</div>
	<?php endif ?>
	<?php if ($this->page->getType() != SxCms_Page::EXTERNAL && $this->page->getType() != SxCms_Page::SUMMARY): ?>
	<div id="tabs-content">
		<?php echo $this->render('page/forms/__content.phtml') ?>
	</div>
	<?php endif ?>
	<?php if ($this->page->getType() != SxCms_Page::ARTICLE): ?>
	<div id="tabs-menu-tags">
		<?php echo $this->render('page/forms/__menu-tags.phtml') ?>
	</div>
	<?php endif ?>
	<?php if ($this->page->getType() == SxCms_Page::INTERNAL): ?>
	<div id="tabs-layout">
		<?php echo $this->render('page/forms/__layout.phtml') ?>
	</div>
	<?php endif ?>
	<div id="tabs-acl">
		<?php echo $this->render('page/forms/__acl.phtml') ?>
	</div>
	<div id="tabs-publish">
		<?php echo $this->render('page/forms/__publish.phtml') ?>
	</div>
    <div id="tabs-seo">
		<?php echo $this->render('page/forms/__seo.phtml') ?>
	</div>
	<div id="tabs-notes">
		<?php echo $this->render('page/forms/__notes.phtml') ?>
		<dl style="margin-top: 25px;">
			<dd>
            <input type="hidden" name="lang" value="<?php echo $_SESSION['System']['lng'] ?>" />
			    <input class="button" type="submit" value="<?php echo $this->admin_tmx->_('save') ?>" onclick="disableConfirm();" />
			</dd>
		</dl>
	</div>
	</form>
</div>
