<?php $this->headScript()->captureStart() ?>
$(function(){
	$('#tabs').tabs();
});
<?php $this->headScript()->captureEnd() ?>

<h3><?php echo $this->admin_tmx->_('page') ?> <?php echo $this->escape($this->page->getTitle()) ?> - <?php echo $this->admin_tmx->_('edit') ?></h3>
<form name="add" method="post" action="<?php echo $this->url() ?>">
	<div id="tabs">
		<ul>
			<li><a href="#tabs-title-summary"><?php echo $this->admin_tmx->_('titlesummary') ?>
				<?php $errors = count($this->messages->getTabMessages('title-summary')) ?>
				<?php if ($errors): ?>
					<span class="errcount">(<?php echo $errors ?>)</span>
				<?php endif ?>
				</a>
			</li>
			<?php if ($this->page->getType() == SxCms_Page::EXTERNAL): ?>
			<li><a href="#tabs-external"><?php echo $this->admin_tmx->_('externalurl') ?>
				<?php $errors = count($this->messages->getTabMessages('external')) ?>
				<?php if ($errors): ?>
					<span class="errcount">(<?php echo $errors ?>)</span>
				<?php endif ?>
				</a>
			</li>
			<?php endif ?>
			<?php if ($this->page->getType() != SxCms_Page::EXTERNAL): ?>
			<li><a href="#tabs-content"><?php echo $this->admin_tmx->_('content') ?>
				<?php $errors = count($this->messages->getTabMessages('content')) ?>
				<?php if ($errors): ?>
					<span class="errcount">(<?php echo $errors ?>)</span>
				<?php endif ?>
				</a>
			</li>
			<?php endif ?>
			<li><a href="#tabs-menu-tags"><?php echo $this->admin_tmx->_('menutags') ?>
				<?php $errors = count($this->messages->getTabMessages('menu-tags')) ?>
				<?php if ($errors): ?>
					<span class="errcount">(<?php echo $errors ?>)</span>
				<?php endif ?>
				</a>
			</li>
			<?php if ($this->page->getType() != SxCms_Page::EXTERNAL): ?>
			<li><a href="#tabs-layout"><?php echo $this->admin_tmx->_('layout') ?>
				<?php $errors = count($this->messages->getTabMessages('layout')) ?>
				<?php if ($errors): ?>
					<span class="errcount">(<?php echo $errors ?>)</span>
				<?php endif ?>
				</a>
			</li>
			<?php endif ?>
			<li><a href="#tabs-publish"><?php echo $this->admin_tmx->_('publication') ?>
				<?php $errors = count($this->messages->getTabMessages('publish')) ?>
				<?php if ($errors): ?>
					<span class="errcount">(<?php echo $errors ?>)</span>
				<?php endif ?>
				</a>
			</li>
			<li><a href="#tabs-notes"><?php echo $this->admin_tmx->_('save') ?></a></li>
		</ul>
		<div id="tabs-title-summary">
			<?php echo $this->render('page/forms/__summary.phtml') ?>
		</div>
		<?php if ($this->page->getType() == SxCms_Page::EXTERNAL): ?>
		<div id="tabs-external">
			<?php echo $this->render('page/forms/__external.phtml') ?>
		</div>
		<?php endif ?>
		<?php if ($this->page->getType() != SxCms_Page::EXTERNAL): ?>
		<div id="tabs-content">
			<?php echo $this->render('page/forms/__content.phtml') ?>
		</div>
		<?php endif ?>
		<div id="tabs-menu-tags">
			<?php echo $this->render('page/forms/__menu-tags.phtml') ?>
		</div>
		<?php if ($this->page->getType() != SxCms_Page::EXTERNAL): ?>
		<div id="tabs-layout">
			<?php echo $this->render('page/forms/__layout.phtml') ?>
		</div>
		<?php endif ?>
		<div id="tabs-publish">
			<?php echo $this->render('page/forms/__publish.phtml') ?>
		</div>
		<div id="tabs-notes">
			<?php echo $this->render('page/forms/__notes.phtml') ?>
			<dl>
				<dd>
				    <input class="button" type="submit" value="<?php echo $this->admin_tmx->_('save') ?>" />
				</dd>
			</dl>
		</div>
	</div>
</form>
