<?php echo $this->render('system/leave.phtml'); ?>

<?php $this->headScript()->appendFile($this->baseUrl() . '/js/tiny_mce/tiny_mce.js') ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/js/tiny_mce/tiny_mce_init.js') ?>

<?php $this->headScript()->captureStart() ?>
$(function(){
	$('#tabs').tabs();
	$("#datePublished").datepicker({dateFormat: 'dd-mm-yy', minDate: '0' });
	$("#dateExpired").datepicker({dateFormat: 'dd-mm-yy', minDate: '0' });
});
<?php $this->headScript()->captureEnd() ?>
<div id="alert" title="Formulier validatie" style="display: none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	Er zijn verplichte velden die niet werden ingevuld.</p>
</div>

<div id="tabs">
	<ul>
		<li><a href="#tabs-survey">Enqu&#234;te
			<?php $errors = count($this->messages->getTabMessages('survey')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
		<li><a href="#tabs-questions">Vragen
			<?php $errors = count($this->messages->getTabMessages('questions')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
		<li><a href="#tabs-answers">Antwoorden
			<?php $errors = count($this->messages->getTabMessages('answers')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
		<li><a href="#tabs-save">Opslaan</a></li>
	</ul>
	<form name="add" method="post" action="<?php echo $this->url() ?>">
	<div id="tabs-survey">
		<?php echo $this->render('survey/forms/__survey.phtml') ?>
	</div>
	<div id="tabs-questions">
		<?php echo $this->render('survey/forms/__questions.phtml') ?>
	</div>
	<div id="tabs-answers">
		<?php echo $this->render('survey/forms/__answers.phtml') ?>
	</div>
	<div id="tabs-save">
		<dl>
			<dd>
			    <input class="button" type="submit" value="Opslaan" onclick="disableConfirm();" />
			</dd>
		</dl>
	</div>
	</form>
</div>