<?php

$user = Zend_Auth::getInstance()->getIdentity();
$this->headScript()->appendFile($this->baseUrl() . '/js/dialog.js');

$this->headTitle('SxCms - Enquetes overzicht');
echo $this->render('system/result.phtml');

$canEdit    = $user->isAllowed('survey', 'survey.edit');
$canDelete  = $user->isAllowed('survey', 'survey.delete');

?>

<div id="dialog" title="Enqu&#234;te verwijderen" style="display: none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	Weet u zeker dat u deze enqu&#234;te wilt verwijderen?</p>
</div>

<h3>Enqu&#234;te overzicht</h3>
<table width="98%">
	<tr>
		<th>Titel</th>
		<th>Vanf</th>
		<th>Tot</th>
		<th>Actie</th>
	</tr>
	<?php foreach ($this->paginator as $id => $item): ?>
	<tr>
		<td><?php echo $this->escape($item->getTitle()) ?></td>
		<td><?php echo $this->escape($item->getDatePublished('%d/%m/%Y')) ?></td>
		<td><?php echo $this->escape($item->getDateExpired('%d/%m/%Y')) ?></td>
		<td>
			<?php if ($canEdit): ?>
			<a title="Inhoud aanpassen" href="<?php echo $this->url(array('controller' => 'survey', 'action' => 'edit', 'id' => $item->getId())) ?>">
				<img src="<?php echo $this->baseUrl('/images/cms/actions/page_white_edit.png') ?>" alt="edit" />
			</a>
			<?php endif ?>
			<?php if ($canDelete): ?>
			<a title="Verwijderen" class="delete" href="#" onclick="showDialog('#dialog', '<?php echo $this->url(array('controller' => 'survey', 'action' => 'delete', 'id' => $item->getId())) ?>');">
				<img src="<?php echo $this->baseUrl('/images/cms/actions/page_white_delete.png') ?>" alt="edit" />
			</a>
			<?php endif ?>
		</td>
	</tr>
	<?php endforeach ?>
</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'system/pagination.phtml'); ?>
