<dl>
	<dt>
		<label for="mailRemember"><?php echo $this->admin_tmx->_('reminderemail') ?>:</label>
	</dt>
	<dd>
		<div id="content_">
			<textarea name="mailRemember" id="mailRemember" style="width:100%; height: 500px;" rows="50" class="mceEditor"><?php echo $this->escape($this->event->getMailRemember()) ?></textarea>
		</div>
	    <?php echo $this->messages->getMessagesHtml('mailRemember') ?>
	    <p class="description">
	        <?php echo $this->admin_tmx->_('requiredmin2chars') ?>
	    </p>
	</dd>

	<dt>
		<label for="mailConfirmation"><?php echo $this->admin_tmx->_('confirmationemail') ?>:</label>
	</dt>
	<dd>
		<div id="content_">
			<textarea name="mailConfirmation" id="mailConfirmation" style="width:100%; height: 500px;" rows="50" class="mceEditor"><?php echo $this->escape($this->event->getMailConfirmation()) ?></textarea>
		</div>
	    <?php echo $this->messages->getMessagesHtml('mailConfirmation') ?>
	    <p class="description">
	        <?php echo $this->admin_tmx->_('requiredmin2chars') ?>
	    </p>
	</dd>
</dl>