<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl('/css/SxCms.css') ?>" type="text/css" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl('/js/jquery-ui/css/custom-theme/jquery-ui-1.7.2.custom.css') ?>" type="text/css" />
	
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
	<?php echo $this->headTitle() ?>
	
	
</head>
<body>
<div id="wrap">
	<div id="header">
		<span id="slogan">Content Management System</span>
	</div>

	<div id="header-logo">
		<div id="logo">SX<span class="green">CMS</span></div>
	</div>

    <?php echo $this->render('__layout/support.phtml') ?>
	<div id="main">
		<?php echo $this->layout()->content ?>
	</div>
</div>

<?php echo $this->render('__layout/footer.phtml') ?>
</body>
</html>
