<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl('/css/SxCms.css') ?>" type="text/css" />
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
	<?php echo $this->headTitle() ?>

	<style type="text/css">
	body { background-image: none; }
	</style>
</head>
<body>
	<?php echo $this->layout()->content ?>
</body>
</html>
