<dl>
    <dt>
		<label for="subject"><?php echo $this->admin_tmx->_('subject') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="subject" id="subject"
	    	value="<?php echo $this->item->getSubject() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('subject') ?>
	    <p class="description"><?php echo $this->admin_tmx->_('subjectdescription') ?></p>
	</dd>

    <dt>
        <label for="Content"><?php echo $this->admin_tmx->_('content') ?>:</label>
    </dt>
    <dd>
        <p class="description"><?php echo $this->admin_tmx->_('contentdescription') ?>:<br />
       <?php echo $this->admin_tmx->_('url') ?> [<?php echo $this->admin_tmx->_('url') ?>] , <?php echo $this->admin_tmx->_('name') ?> = [<?php echo $this->admin_tmx->_('naam') ?>] , <?php echo $this->admin_tmx->_('firstname') ?> = [<?php echo $this->admin_tmx->_('firstname') ?>]</p>
        <textarea name="content" id="content" style="width:100%; height: 500px;" rows="50" class="mceEditor"><?php echo $this->escape($this->item->getContent()) ?></textarea>
        <?php echo $this->messages->getMessagesHtml('content') ?>
    </dd>
</dl>