<h3 id="menu-action"><a href="#">Acties</a></h3>
<div>
<strong>Acties</strong>
	<ul class="sidemenu">
		<li><a href="<?php echo $this->url(array('controller' => 'action', 'action' => 'index'), null, true) ?>">Overzicht</a></li>
      	<li><a href="<?php echo $this->url(array('controller' => 'action', 'action' => 'add'), null, true) ?>">Toevoegen</a></li>
	</ul>
<strong>Types</strong>
	<ul class="sidemenu">
		<li><a href="<?php echo $this->url(array('controller' => 'action_type', 'action' => 'index'), null, true) ?>">Overzicht</a></li>
      	<li><a href="<?php echo $this->url(array('controller' => 'action_type', 'action' => 'add'), null, true) ?>">Toevoegen</a></li>
	</ul>
</div>

