<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/dialog.js');

$this->headTitle('SxCms - Types overzicht');
echo $this->render('system/result.phtml');
?>
<script type="text/javascript">
$(document).ready(function() {
var fixHelper = function(e, ui) {
    ui.children().each(function() {
        $(this).width($(this).width());
    });
    return ui;
};
    $('#sort').sortable({
      helper: fixHelper,
      handle : '.handle',
      update : function () {
        var order = $('#sort').sortable('serialize', 'id');
        move(order);
      }
    }).disableSelection();;
});

function move(order){
    var data = order;
    var url = '/admin/faq_type/ranking';
    var dataType = 'script';
    var type = 'POST';
     $.ajax({
        type: type,
        url: url,
        data: data,
        dataType: dataType,
        success: function(){
            location.reload();
        }
    });
}
</script>

<div id="dialog" title="Type verwijderen" style="display: none;">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
        Weet u zeker dat u dit type wilt verwijderen?<br /> 
        <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px  0 -23px;"></span><strong>Opgelet: De bestaande acties van dit type zullen ook verwijderd worden !</strong></p>
</div>

<table width="98%">
    <tr>
        <th width="15"></th>
        <th>Naam Type</th>
        <th width="40px">Actief</th>
        <th width="70px">Actie</th>
    </tr>
    <tbody id="sort">
    <?php foreach ($this->paginator as $id => $item): ?>

        <tr id="listItem_<?php echo $item->getTypeId();?>">
            <td width="15"><img src="<?php echo $this->baseUrl('/images/cms/actions/page.png') ?>" alt="" class="handle"/></td>
            <td><?php echo $this->escape($item->getName()) ?></td>
            <td>
                <a title="Activeren/Deactiveren" href="<?php echo $this->url(array('action' => 'activate', 'id' => $item->getTypeId())) ?>">
                    <?php if ($item->getActive()) : ?>
                        <center><img src="<?php echo $this->baseUrl('/ico/tick-circle.png') ?>" alt="de-actief?" /></center>
                    <?php else : ?>
                        <center><img src="<?php echo $this->baseUrl('/ico/minus-circle.png') ?>" alt="activeer?" /></center>
                    <?php endif ?> 
                </a> 
            </td>
            <td>

                <a title="Aanpassen" href="<?php echo $this->url(array('action' => 'edit', 'id' => $item->getTypeId())) ?>">
                    <img src="<?php echo $this->baseUrl('/images/cms/actions/page_white_edit.png') ?>" alt="Aanpassen" />
                </a>

                <!--
                <a title="Vragen" href="<?php echo $this->url(array('controller' => 'faq', 'action' => 'select', 'type' => $item->getId())) ?>">
                                    <img src="<?php echo $this->baseUrl('/images/cms/actions/page_go.png') ?>" alt="Aanpassen" />
                            </a>-->


                <a title="Verwijderen" class="delete" href="#" onclick="showDialog('#dialog', '<?php echo $this->url(array('action' => 'delete', 'id' => $item->getTypeId())) ?>');">
                    <img src="<?php echo $this->baseUrl('/images/cms/actions/page_white_delete.png') ?>" alt="Verwijderen" />
                </a>




            </td>
        </tr>


    <?php endforeach ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'system/pagination.phtml'); ?>
