<dl>
    <dt>
        <label for="blockname"><?php echo $this->admin_tmx->_('blockname') ?>:</label>
    </dt>
    <dd>
        <input type="text" name="blockname" id="blockname" size="90"
               value="<?php echo $this->escape($this->block->getBlockname()) ?>" />
               <?php echo $this->messages->getMessagesHtml('blockname') ?>
        <p class="description">
            <?php echo $this->admin_tmx->_('min2max255chars') ?>
        </p>
    </dd>
    
    <dt>
        <label for="picture"><?php echo $this->admin_tmx->_('picture') ?>:</label>
    </dt>
    <dd>
        <input type="file" name="picture" id="picture" size="90" value="" />
        <?php echo $this->messages->getMessagesHtml('picture') ?>
        <?php echo $this->messages->getMessagesHtml('file') ?>
        <p class="description">
            <?php echo $this->admin_tmx->_('picturesizerestrictions') ?>
            <?php if($this->block->getPicture()) : ?>
            <br />
            <img src="/images/topcontentblock/large/<?php echo $this->block->getPicture(); ?>" alt=""  />
            <?php endif; ?>
        </p>
    </dd>
    
    <dt>
        <label for="thumb"><?php echo $this->admin_tmx->_('thumb') ?>:</label>
    </dt>
    <dd>
        <input type="file" name="thumb" id="thumb" size="90" value="" />
        <?php echo $this->messages->getMessagesHtml('thumb') ?>
        <?php echo $this->messages->getMessagesHtml('file') ?>
        <p class="description">
            <?php echo $this->admin_tmx->_('picturesizerestrictions') ?>
            <?php if($this->block->getPicture()) : ?>
            <br />
            <img src="/images/topcontentblock/thumb/<?php echo $this->block->getThumb(); ?>" alt=""  />
            <?php endif; ?>
        </p>
    </dd>
    
    
    <br />
    <dd>
        <input class="button" type="submit" value="<?php echo $this->admin_tmx->_('save') ?>" onclick="disableConfirm();" />
    </dd>

</dl>