<?php echo $this->render('system/leave.phtml'); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/js/tiny_mce/tiny_mce.js') ?>
<?php include('tiny_mce_init.php'); ?>

<?php $this->headScript()->captureStart() ?>
$(function(){
	$('#tabs').tabs();
    $("#date_published").datepicker({ dateFormat: 'yy/mm/dd' });
    $("#date_expired").datepicker({ dateFormat: 'yy/mm/dd' });
});
<?php $this->headScript()->captureEnd() ?>
<div id="alert" title="<?php echo $this->admin_tmx->_('formvalidation') ?>" style="display: none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?php echo $this->admin_tmx->_('allfieldsrequired') ?></p>
</div>

<div id="tabs">
	<ul>
		<li><a href="#tabs-settings"><?php echo $this->admin_tmx->_('settings') ?>
			<?php $errors = count($this->messages->getTabMessages('settings')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
        <li><a href="#tabs-content"><?php echo $this->admin_tmx->_('message') ?>
			<?php $errors = count($this->messages->getTabMessages('content')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
        <li><a href="#tabs-image">Afbeelding
			<?php $errors = count($this->messages->getTabMessages('image')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
		<li><a href="#tabs-seo"><?php echo $this->admin_tmx->_('seo') ?>
			<?php $errors = count($this->messages->getTabMessages('seo')) ?>
			<?php if ($errors): ?>
				<span class="errcount">(<?php echo $errors ?>)</span>
			<?php endif ?>
			</a>
		</li>
		<li><a href="#tabs-save"><?php echo $this->admin_tmx->_('save') ?></a></li>
	</ul>
    <form name="add" method="post" action="<?php echo $this->url() ?>" enctype="multipart/form-data">
	<div id="tabs-settings">
		<?php echo $this->render('news/forms/__settings.phtml') ?>
	</div>
	<div id="tabs-content">
		<?php echo $this->render('news/forms/__content.phtml') ?>
	</div>
	<div id="tabs-image">
		<?php echo $this->render('news/forms/__image.phtml') ?>
	</div>
	<div id="tabs-seo">
		<?php echo $this->render('news/forms/__seo.phtml') ?>
	</div>
	<div id="tabs-save">
		<dl>
                    <input type="hidden" id="lang" name="lang" value="<?php echo $this->item->getLng(); ?>" />
			<dd>
			    <input class="button" type="submit" value="<?php echo $this->admin_tmx->_('save') ?>" onclick="disableConfirm();$('#select2 option').attr('selected','selected');$('#select4 option').attr('selected','selected');$('#select6 option').attr('selected','selected');$('#select8 option').attr('selected','selected');$('#select10 option').attr('selected','selected');" />
			</dd>
		</dl>
	</div>
	</form>
</div>