<?php $this->placeholder('header')->set('contact') ?>

<div class="container_12">
    <img class="coffee-cup" src="<?php echo $this->baseUrl("/images/website/cup.gif"); ?>"/>
    <?php echo $this->page->getContent(); ?>
    <form class="form contact-form" name="contact-form" method="post" action="<?php echo $this->url() ?>" id="contact-form">
        <?php if ($this->errors): ?>
            <?php $errors = $this->errors; ?>
        <?php endif ?>

        <div class="form-line">
            <?php if (isset($errors['email']) && is_array($errors['email'])) : ?>
                <p class="error"><?php foreach ($errors['email'] as $error) : echo $error; endforeach; ?></p>
            <?php endif; ?>
            <div class="form-value">
                <input required placeholder="Email Address" type="text" name="email" value="<?php echo $this->contact->getEmail() ?>" />
            </div>
            <div class="clear"></div>
        </div>

        <div class="form-line">
            <?php if (isset($errors['message']) && is_array($errors['message'])) : ?>
                <p class="error"><?php foreach ($errors['message'] as $error) : echo $error; endforeach; ?></p>
            <?php endif; ?>
            <div class="form-value">
                <textarea required placeholder="Your Message" name="message"><?php echo $this->contact->getMessage() ?></textarea>
            </div>
            <div class="clear"></div>
        </div>

        <div class="form-line">
            <label>&nbsp;</label>
            <div class="form-value">
                <button type="submit" class="submit grow" name="submit" value="contact">
                    <?php echo $this->tmx->_('btn.send'); ?>
                </button>
                <input type="hidden" name="submit" value="contact"/>
            </div>
            <div class="clear"></div>
        </div>
    </form>
	<div class="clear"></div>		
</div>



