<?php $this->headScript()->appendFile($this->baseUrl() . '/js/tiny_mce/tiny_mce.js') ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/js/tiny_mce/tiny_mce_init.js') ?>

<?php echo $this->render('system/leave.phtml'); ?>
<?php $this->headScript()->captureStart() ?>
$(function(){
	$('#tabs').tabs();
});
<?php $this->headScript()->captureEnd() ?>

<?php echo $this->render('system/result.phtml') ?>
<h3>Content block aanpassen</h3>

<div id="tabs">
	<ul>
		<?php foreach ($this->blocks as $key => $zone): ?>
		<li><a href="#tabs-<?php echo $zone->id ?>"><?php echo $zone->name ?></a></li>
		<?php endforeach ?>
	</ul>

	<form name="add" method="post" action="<?php echo $this->url() ?>">
	<?php foreach ($this->blocks as $key => $zone): ?>
	<div id="tabs-<?php echo $zone->id ?>">
		<dl>
			<dt>
				<label>Inhoud:</label>
			</dt>
			<dd>
				<textarea name="blocks[<?php echo $zone->id ?>]" style="width:100%; height: 500px;" rows="50" class="mceEditor"><?php echo $zone->content ?></textarea>
			</dd>
			<dd style="padding-top: 25px;">
			    <input class="button" type="submit" value="Opslaan" onclick="disableConfirm();" />
			</dd>
		</dl>
	</div>
	<?php endforeach ?>
	</form>
</div>
