<dl>
	<dt>
		<label for="name">Titel:</label>
	</dt>
	<dd>
	    <input type="text" name="name" id="name"
	    	value="<?php echo $this->type->getName() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('name') ?>
	    <p class="description">
	      
	    </p>
	</dd>
    <?php /*
     <dt>
		<label for="stop">Actief</label>
	</dt>
	<dd>
    	<input type="checkbox" name="active" id="active" value="1" <?php if($this->type->getActive()): ?>checked="checked"<?php endif ?> />
	    <p class="description"></p>
	</dd>*/ ?>
	
</dl>