<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/dialog.js');
$user = Zend_Auth::getInstance()->getIdentity();

$canActivate = $user->isAllowed('sheets', 'sheets.activate');
$canDelete = $user->isAllowed('sheets', 'sheets.delete');
$canRanking = $user->isAllowed('sheets','sheets.ranking');
$this->headTitle('SxCms - '.$this->admin_tmx->_('typeoverview'));
echo $this->render('system/result.phtml');
?>
<?php if($canRanking){ ?>
<script type="text/javascript">
$(document).ready(function() {
var fixHelper = function(e, ui) {
    ui.children().each(function() {
        $(this).width($(this).width());
    });
    return ui;
};
    $('#sort').sortable({
      helper: fixHelper,
      handle : '.handle',
      update : function () {
        var order = $('#sort').sortable('serialize', 'id');
        move(order);
      }
    }).disableSelection();;
});

function move(order){
    var data = order;
    var url = '/admin/sheets_type/ranking';
    var dataType = 'script';
    var type = 'POST';
     $.ajax({
        type: type,
        url: url,
        data: data,
        dataType: dataType,
        success: function(){
            location.reload();
        }
    });
}
</script>
<?php } ?>
<div id="dialog" title="<?php echo $this->admin_tmx->_('deletetype') ?>" style="display: none;">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
        <?php echo $this->admin_tmx->_('deletetypeconfirm') ?><br /> 
        <span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px  0 -23px;"></span><strong><?php echo $this->admin_tmx->_('deletetypewarning') ?></strong></p>
</div>

<table width="98%">
    <tr>
        <th width="15"></th>
        <th><?php echo $this->admin_tmx->_('nametype') ?></th>
        <th width="40px"><?php echo $this->admin_tmx->_('active') ?></th>
        <th width="40px"><?php echo $this->admin_tmx->_('amountsubtypes') ?></th>
        <th width="70px"><?php echo $this->admin_tmx->_('action') ?></th>
    </tr>
    <tbody id="sort">
    <?php foreach ($this->paginator as $id => $item): ?>

        <tr id="listItem_<?php echo $item->getId();?>">
            <td width="15"><img src="<?php echo $this->baseUrl('/images/cms/actions/page.png') ?>" alt="" class="handle"/></td>
            <td><?php echo $this->escape($item->getName()) ?></td>
            <td>
		<?php if($canActivate): ?>
                <a title="<?php echo $this->admin_tmx->_('activatedeactivate') ?>" href="<?php echo $this->url(array('action' => 'activate', 'id' => $item->getId())) ?>">
                    <?php endif ?><?php if ($item->getActive()) : ?>
                        <center><img src="<?php echo $this->baseUrl('/ico/tick-circle.png') ?>" alt="de-actief?" /></center>
                    <?php else : ?>
                        <center><img src="<?php echo $this->baseUrl('/ico/minus-circle.png') ?>" alt="activeer?" /></center>
                    <?php endif ?> 
                        <?php if($canActivate): ?></a> <?php endif ?>
            </td>
            <td style="text-align: center;">
		
                <?php echo count($item->getSubtypes()); ?>
            </td>
            <td>
                <a title="<?php echo $this->admin_tmx->_('addsubtype') ?>" href="<?php echo $this->url(array('controller' => 'sheets_subtype', 'action' => 'index', 'type' => $item->getId())) ?>">
                                    <img src="<?php echo $this->baseUrl('/ico/plus-circle.png') ?>" alt="<?php echo $this->admin_tmx->_('edit') ?>" />
                </a>

                <a title="<?php echo $this->admin_tmx->_('edit') ?>" href="<?php echo $this->url(array('action' => 'edit', 'id' => $item->getId())) ?>">
                    <img src="<?php echo $this->baseUrl('/images/cms/actions/page_white_edit.png') ?>" alt="<?php echo $this->admin_tmx->_('edit') ?>" />
                </a>

                <?php /*<!--
                <a title="Vragen" href="<?php echo $this->url(array('controller' => 'sheets_subtype', 'action' => 'select', 'type' => $item->getId())) ?>">
                                    <img src="<?php echo $this->baseUrl('/images/cms/actions/page_go.png') ?>" alt="Aanpassen" />
                            </a>-->*/ ?>

		<?php if($canDelete): ?>
                <a title="<?php echo $this->admin_tmx->_('delete') ?>" class="delete" href="#" onclick="showDialog('#dialog', '<?php echo $this->url(array('action' => 'delete', 'id' => $item->getId())) ?>');">
                    <?php endif ?><img src="<?php echo $this->baseUrl('/images/cms/actions/page_white_delete.png') ?>" alt="<?php echo $this->admin_tmx->_('delete') ?>" />
                <?php if($canDelete):?></a><?php endif?>




            </td>
        </tr>


    <?php endforeach ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'system/pagination.phtml'); ?>