 <div id="header">
     <a title="Terug naar de homepage" href="<?php echo $this->baseUrl() ?>">
         <img src="<?php echo $this->baseUrl('/images/website/logo.jpg') ?>" alt="KLAV" id="logo" />
     </a>
     <div id="menufull">
         <?php echo $this->action('multilevelmenu' , 'index' , null , array('page' => $this->page, 'lng' => $this->lng)) ?>

     </div>
 </div>
 <div style="clear: both;"></div>