<dl>
    <dt>
		<label for="subject"><?php echo $this->admin_tmx->_('subjectemail') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="subject" id="subject"
	    	value="<?php echo $this->item->getSubject() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('subject') ?>
	    <p class="description"><?php echo $this->admin_tmx->_('subjectemaildescription') ?></p>
	</dd>

    <dt>
        <label for="Content"><?php echo $this->admin_tmx->_('content') ?>:</label>
    </dt>
    <dd>
        <?php echo $this->messages->getMessagesHtml('content') ?>
        <p class="description"><?php echo $this->admin_tmx->_('contentdescriptions') ?></p>
        <textarea name="content" id="content" style="width:100%; height: 500px;" rows="50" class="mceEditor"><?php echo $this->escape($this->item->getContent()) ?></textarea>
    </dd>
</dl>