<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('/css/SxCms.css') ?>" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('/js/jquery-ui/css/custom-theme/jquery-ui-1.7.2.custom.css') ?>" type="text/css" />

<?php /*<script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery-1.3.2.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery-ui/js/jquery-ui-1.7.2.custom.min.js') ?>"></script>*/ ?>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>

<script type="text/javascript">
<?php /*$(function() {
    <?php $active = $this->menu['active'] ? $this->menu['active'] : 'page/__menu.phtml'; ?>
    $("#menu").accordion({
        autoHeight: false
        <?php if ($this->menu['active']): ?>
        , active: $("#<?php echo $this->menu['active'] ?>")
        , animated: false
        <?php endif ?>
    });
});*/ ?>
$(document).ready(function() {
	$("#menu").accordion({
        heightStyle: "content"
        <?php if ($this->menu['active']): ?>
	        , active: $("#<?php echo $this->menu['active'] ?>").parent().children('h3').index($("#<?php echo $this->menu['active'] ?>"))
	        , animated: false
        <?php endif ?>
    });
});
</script>

<?php echo $this->headLink() ?>
<?php echo $this->headScript() ?>
<?php echo $this->headTitle() ?>


