<h3 id="menu-webtv"><a href="#"><?php echo $this->admin_menu_tmx->_('wtv.webtv') ?></a></h3>
<div>
	<ul class="sidemenu">
		<li><a href="<?php echo $this->url(array('controller' => 'webtv', 'action' => 'index'), null, true) ?>"><?php echo $this->admin_menu_tmx->_('wtv.overview') ?></a></li>
      	<li><a href="<?php echo $this->url(array('controller' => 'webtv', 'action' => 'add'), null, true) ?>"><?php echo $this->admin_menu_tmx->_('wtv.add') ?></a></li>
	</ul>
</div>

