<?php

$user = Zend_Auth::getInstance()->getIdentity();
$this->headScript()->appendFile($this->baseUrl() . '/js/dialog.js');

$this->headTitle('SxCms - '.$this->admin_tmx->_('webtvoverview'));
echo $this->render('system/result.phtml');

$canActivate = $user->isAllowed('webtv', 'webtv.activate');
$canDelete = $user->isAllowed('webtv', 'webtv.delete');
?>

<div id="dialog" title="Detail verwijderen" style="display: none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	<?php echo $this->admin_tmx->_('deleteconfirm') ?></p>
</div>
<h3><?php echo $this->admin_tmx->_('webtvoverview') ?> [<?php echo strtoupper($_SESSION['System']['lng']); ?>]</h3>
<table width="98%">
	<tr>
		<th><?php echo $this->admin_tmx->_('name') ?></th>
        <th><?php echo $this->admin_tmx->_('publicationdateifactive') ?></th>
        <th width="40px"><?php echo $this->admin_tmx->_('active') ?></th>
		<th width="70px"><?php echo $this->admin_tmx->_('action') ?></th>
	</tr>
	<?php foreach ($this->paginator as $id => $item): ?>
	<tr>
		<td><?php echo $this->escape($item->getTitle()) ?></td>
        <td><?php echo $item->getDatePublished('%d/%m/%Y'); ?></td>
        <td>
             <?php if ($canActivate): ?>
            <a title="<?php echo $this->admin_tmx->_('activatedeactivate') ?>" href="<?php echo $this->url(array('action' => 'activate', 'id' => $item->getId())) ?>">
            <?php endif ?>
                <?php if($item->isActive()) : ?>
                <center><img src="<?php echo $this->baseUrl('/ico/tick-circle.png') ?>" alt="<?php echo $this->admin_tmx->_('deactivate') ?>" /></center>
            <?php else : ?>
                <center><img src="<?php echo $this->baseUrl('/ico/minus-circle.png') ?>" alt="<?php echo $this->admin_tmx->_('activate') ?>" /></center>
			<?php endif ?> 
            </a>
        </td>
		<td>
			<a title="<?php echo $this->admin_tmx->_('edit') ?>" href="<?php echo $this->url(array('action' => 'edit', 'id' => $item->getId())) ?>">
				<img src="<?php echo $this->baseUrl('/images/cms/actions/page_white_edit.png') ?>" alt="<?php echo $this->admin_tmx->_('edit') ?>" />
			</a>
            
			<?php if($canDelete): ?><a title="<?php echo $this->admin_tmx->_('delete') ?>" class="delete" href="#" onclick="showDialog('#dialog', '<?php echo $this->url(array('action' => 'delete', 'id' => $item->getId())) ?>');">
				<?php endif ?><img src="<?php echo $this->baseUrl('/images/cms/actions/page_white_delete.png') ?>" alt="<?php echo $this->admin_tmx->_('delete') ?>" />
			<?php if($canDelete): ?></a><?php endif ?>
		</td>
	</tr>
	<?php endforeach ?>
</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'system/pagination.phtml'); ?>
