<form enctype="multipart/form-data" id="form" name="form" method="post" action="">
	<fieldset>
		<legend><?php echo $this->admin_tmx->_('uploadpictures') ?></legend>

		<label><?php echo $this->admin_tmx->_('picture') ?></label>
		<input type="file" name="picture[]" /><br />
		<label><?php echo $this->admin_tmx->_('picture') ?></label>
		<input type="file" name="picture[]" /><br />
		<label><?php echo $this->admin_tmx->_('picture') ?></label>
		<input type="file" name="picture[]" /><br />

	    <input type="hidden" name="product_id" value="7" />

	    <label for="submit"></label>
    	<input type="submit" name="submit" value="<?php echo $this->admin_tmx->_('save') ?>!" />
	</fieldset>
</form>