<?php
$config = Zend_Registry::get('config');
$company = '<div class="map-infobox">'. $config->company->name . '</div>';
$imageUrl = "/images/website/";
?>

<script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script>
function initialize(){

var geocoder = new google.maps.Geocoder();

geocoder.geocode( { 'address': '<?php echo $config->company->address; ?>'}, function(results, status){

	var latlng = results[0].geometry.location;
    
	var opt ={
	    center:latlng,
	    zoom:15,
	    mapTypeId: google.maps.MapTypeId.ROADMAP,
	    disableAutoPan:false,
	    navigationControl:false,
	    mapTypeControl:false,
	    mapTypeControlOptions: {style:google.maps.MapTypeControlStyle.DROPDOWN_MENU},
	   	disableDefaultUI: true
	};
    
	var map = new google.maps.Map(document.getElementById("map"),opt);
    
	var marker = new google.maps.Marker({
	    position: results[0].geometry.location,
		title: "<?php echo $config->company->name; ?>",
		clickable: true,
		map: map,
        icon: '<?php echo $imageUrl; ?>' + 'marker.png'
	});

	var infiwindow = new google.maps.InfoWindow({
	    content: '<?php echo $company; ?>'
	});

	google.maps.event.addListener(marker,'mouseover',function(){
	infiwindow.open(map,marker);
	});

});

}

window.onload = initialize();
</script>

<div id="map"></div>

