<dl>
	<dd>
		<input type="radio" name="type" value="0" checked="checked" /> <?php echo $this->admin_tmx->_('internalpage') ?><br />
	    <p class="description">
	        <?php echo $this->admin_tmx->_('internalpagedescription') ?>
	    </p>
	</dd>

	<dd style="padding-top: 10px;">
		<input type="radio" name="type" value="1" /> <?php echo $this->admin_tmx->_('externalinternalpage') ?><br />
	    <p class="description">
	        <?php echo $this->admin_tmx->_('externalinternalpagedescription') ?>
	    </p>
	</dd>
	<dd style="padding-top: 10px;">
		<input type="radio" name="type" value="3" /> <?php echo $this->admin_tmx->_('overviewpage') ?><br />
	    <p class="description">
	        <?php echo $this->admin_tmx->_('overviewpagedescription') ?>
	    </p>
	</dd>
</dl>