<?php

echo $this->render('analytics/__js.phtml');

$user = Zend_Auth::getInstance()->getIdentity();

$this->headTitle('SxCms - Analytics - Pagina\'s');

$page = $this->page;
$minpage = $page-4;
$maxpage = $page+4;

if (in_array("last", $this->allpages['path'])) $maxpage = $page;

$pages = array();

$pages[] = "<div style='width: 100%; text-align: center;'>";

if ($page>1) $pages[] = "<span style='font-size: 14px; padding: 10px; font-weight: bold;'><a href='/admin/analytics/allpages/page/".($page-1)."'><</a></span>";

for ($i = $minpage; $i <= $maxpage; $i++) {
	
	if ($i>0) {
		if ($i == $page) {
			$pages[] = "<span style='font-size: 16px; padding: 5px; font-weight: bold;'>$page</span>";
		} else {
			$pages[] = "<span style='padding: 5px;'><a href='/admin/analytics/allpages/page/".($i)."'>$i</a></span>";
		}
	}
	
}

if ($page != $maxpage)
	$pages[] = "<span style='font-size: 14px; padding: 10px; font-weight: bold;'><a href='/admin/analytics/allpages/page/".($page+1)."'>></a></span></div>";

$pagination = implode('', $pages);

?>

<div style='float: left;'><h3>Analytics - Pagina's</h3></div>

<div style='float: right;'><?php echo $this->render('analytics/forms/__top.phtml'); ?></div>
<div style='clear: both'></div>

<?php echo $pagination ?>

<table style='width: 97%;'>
	
	<thead>
		<tr><th>Titel</th><th>URL</th><th title='Gemiddelde laadtijd'>Laadtijd</th><th>Bezoeken</th></tr>
	</thead>
	
	<tbody>
		<?php foreach ($this->allpages['path'] AS $key => $value): ?>
			<?php if ($value != "last"): ?>
				<tr><td title='<?php echo $this->allpages['title'][$key] ?>'><?php echo $this->excerpt($this->allpages['title'][$key], 48, '...') ?></td>
				<td title='<?php echo $value ?>'><a href='<?php echo ($value=="#"?"":"http://") ?><?php echo $value ?>' <?php echo ($value=="#"?"":"target='_blank'") ?>><?php echo $this->excerpt($value, 38, '...') ?></a></td>
				<td title='Gemiddelde laadtijd'><?php echo round($this->allpages['loadtime'][$key], 3) ?> sec</td>
				<td><?php echo $this->allpages['visits'][$key] ?></td></tr>
			<?php endif; ?>
		<?php endforeach; ?>
	</tbody>
	
</table>

<?php echo $pagination ?>