<dl>
    <dt>
		<label for="stop"><?php echo $this->admin_tmx->_('active') ?></label>
	</dt>
    <dd>
    	<input type="checkbox" name="active" id="active" value="1" <?php if($this->item->getActive()): ?>checked="checked"<?php endif ?> />
	    <p class="description"></p>
	</dd>

    <dt>
		<label for="sex"><?php echo $this->admin_tmx->_('sex') ?>:</label>
	</dt>
    <dd>
        <select name="sex" id="sex">
            <option value=""><?php echo $this->admin_tmx->_('choosesex') ?></option>
            <option value="M" <?php if($this->item->getSex() == 'M'): ?>selected="selected"<?php endif ?>><?php echo $this->admin_tmx->_('male') ?></option>
            <option value="V" <?php if($this->item->getSex() == 'V'): ?>selected="selected"<?php endif ?>><?php echo $this->admin_tmx->_('female') ?></option>
        </select>
	    <p class="description"></p>
	</dd>

	<dt>
		<label for="name"><?php echo $this->admin_tmx->_('name') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="name" id="name"
	    	value="<?php echo $this->item->getName() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('name') ?>
	    <p class="description">
	        <?php echo $this->admin_tmx->_('requiredmin2chars') ?><br />
	    </p>
	</dd>
    
    <dt>
		<label for="firstname">Voornaam:</label>
	</dt>
	<dd>
	    <input type="text" name="first_name" id="first_name"
	    	value="<?php echo $this->item->getFirstName() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('first_name') ?>
	    <p class="description">
	        <?php echo $this->admin_tmx->_('requiredmin2chars') ?><br />
	    </p>
	</dd>

    <dt>
		<label for="company"><?php echo $this->admin_tmx->_('company') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="company" id="company"
	    	value="<?php echo $this->item->getCompany() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('company') ?>
	    <p class="description"></p>
	</dd>

    <dt>
		<label for="website"><?php echo $this->admin_tmx->_('website') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="website" id="website"
	    	value="<?php echo $this->item->getWebsite() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('website') ?>
	    <p class="description"></p>
	</dd>

    <dt>
		<label for="email"><?php echo $this->admin_tmx->_('email') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="email" id="email"
	    	value="<?php echo $this->item->getEmail() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('email') ?>
	    <p class="description"><?php echo $this->admin_tmx->_('descriptionemail') ?></p>
	</dd>

    <dt>
		<label for="password"><?php echo $this->admin_tmx->_('password') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="password" id="password"
	    	value="<?php echo $this->item->getPassword() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('password') ?>
	    <p class="description"><?php echo $this->admin_tmx->_('passworddescription') ?></p>
	</dd>

    <dt>
		<label for="phone"><?php echo $this->admin_tmx->_('phone') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="phone" id="phone"
	    	value="<?php echo $this->item->getPhone() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('phone') ?>
	    <p class="description"></p>
	</dd>

    <dt>
		<label for="fax"><?php echo $this->admin_tmx->_('fax') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="fax" id="fax"
	    	value="<?php echo $this->item->getFax() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('fax') ?>
	    <p class="description"></p>
	</dd>

    <dt>
		<label for="mobilephone"><?php echo $this->admin_tmx->_('mobile') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="mobile_phone" id="mobile_phone"
	    	value="<?php echo $this->item->getMobilePhone() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('mobile_phone') ?>
	    <p class="description"></p>
	</dd>

    <dt>
		<label for="Street"><?php echo $this->admin_tmx->_('streetnumber') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="street" id="street"
	    	value="<?php echo $this->item->getStreet() ?>" style="width: 180px;" />
        <input type="text" name="number" id="number"
	    	value="<?php echo $this->item->getNumber() ?>" style="width: 50px; margin-left: 20px;" />
	    <?php echo $this->messages->getMessagesHtml('street') ?>
        <?php echo $this->messages->getMessagesHtml('number') ?>
	    <p class="description"></p>
	</dd>

    <dt>
		<label for="postalcode"><?php echo $this->admin_tmx->_('postaltown') ?>:</label>
	</dt>
	<dd>
        <input type="text" name="postalcode" id="postalcode"
	    	value="<?php echo $this->item->getPostalcode() ?>" style="width: 50px; margin-right: 20px;" />
	    <input type="text" name="place" id="place"
	    	value="<?php echo $this->item->getPlace() ?>" style="width: 180px;" />
	    <?php echo $this->messages->getMessagesHtml('postalcode') ?>
        <?php echo $this->messages->getMessagesHtml('place') ?>
	    <p class="description"></p>
	</dd>

    <dt>
		<label for="country"><?php echo $this->admin_tmx->_('country') ?>:</label>
	</dt>
	<dd>
	    <input type="text" name="country" id="country"
	    	value="<?php echo $this->item->getCountry() ?>" style="width: 250px;" />
	    <?php echo $this->messages->getMessagesHtml('country') ?>
	    <p class="description"></p>
	</dd>

</dl>